---
abstract: 'Log::Minimal middleware to prints to psgi.errors'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Log-Minimal
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Log::Minimal: 0.06
  Plack::Middleware: 0
  Term::ANSIColor: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Plack-Middleware-Log-Minimal.git
version: 0.03
